# Generated by Django 5.2.17 on 2026-09-13 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', '진행 중'), ('completed', '완료'), ('archived', '보관')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('value_json', models.JSONField()),
                ('normalized_value', models.CharField(db_index=True, max_length=300)),
                ('source_type', models.CharField(choices=[('chat', '채팅'), ('document', '문서 OCR'), ('user', '사용자 확인')], max_length=16)),
                ('source_ref', models.CharField(max_length=100)),
                ('source_label', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('active', '확인'), ('conflict', '충돌'), ('invalidated', '무효')], db_index=True, default='active', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='cases.contractcase')),
            ],
            options={
                'ordering': ('key', '-observed_at'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('document', '문서')], max_length=16)),
                ('original_name', models.CharField(max_length=180)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('processing_status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('ready', '완료'), ('failed', '실패'), ('deleted', '삭제')], default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('analysis_json', models.JSONField(blank=True, default=dict)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.contractcase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content_json', models.JSONField(default=dict)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('generation_mode', models.CharField(default='llm', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.contractcase')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('rule_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('candidate', '승인 대기'), ('confirmed', '확정'), ('dismissed', '제외')], default='candidate', max_length=16)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='cases.contractcase')),
                ('source_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casefact')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('state', models.CharField(choices=[('todo', '확인 필요'), ('done', '완료'), ('dismissed', '제외')], default='todo', max_length=16)),
                ('auto_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casefact')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='cases.contractcase')),
            ],
            options={
                'ordering': ('priority', 'id'),
                'constraints': [models.UniqueConstraint(fields=('case', 'code'), name='unique_case_checklist')],
            },
        ),
        migrations.AddIndex(
            model_name='casefact',
            index=models.Index(fields=['case', 'key', 'status'], name='cases_casef_case_id_967cfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='casefact',
            constraint=models.UniqueConstraint(fields=('case', 'key', 'normalized_value', 'source_type', 'source_ref'), name='unique_fact_assertion'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('case', 'sha256', 'kind'), name='unique_case_attachment'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('case', 'version'), name='unique_case_report_version'),
        ),
        migrations.AddConstraint(
            model_name='scheduleevent',
            constraint=models.UniqueConstraint(fields=('case', 'rule_code', 'starts_at'), name='unique_case_schedule'),
        ),
    ]
