# Generated by Django 5.2.17 on 2026-09-10 07:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('busy_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(editable=False, null=True)),
            ],
        ),
    ]
