# Generated by Django 5.2.17 on 2026-09-11 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('metadata', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LawAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.lawwatch')),
            ],
        ),
    ]
