# Generated by Django 5.2.17 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_pendingdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="active_request_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
